pipeline {
  environment {
    MSBUILD = "C:\Program Files\Microsoft Visual Studio\2022\Community\Msbuild\Current\Bin\"
    CONFIG = 'Release'
    PLATFORM = 'x86'
  }
  stages {
    stage('Build') {
      steps {
        bat "\"${MSBUILD}\" /p:Configuration=${env.CONFIG}; /p:AppxBundlePlatforms=${env.PLATFORM}  /p:AppxBundle=Never /p:UapAppxPackageBuildMode=Sideloading  /p:AppxPackageSigningEnabled=false
        
      }
    }
  }
}